#!/bin/bash

# check hosts exists
if ! host test-mgmt &> /dev/null
then
  echo "ERROR: test-mgmt server does not exists, check cloud!"
  exit 1
fi

if ! host test-vpn &> /dev/null
then
  echo "ERROR: test-vpn server does not exists, check cloud!"
  exit 1
fi

if ! host test-ca &> /dev/null
then
  echo "ERROR: test-ca server does not exists, check cloud!"
  exit 1
fi

if ! host test-mon &> /dev/null
then
  echo "ERROR: test-mon server does not exists, check cloud!"
  exit 1
fi

# set permissions on scripts
chown -R smailik:smailik /opt/my-scripts
chmod -R 700 /opt/my-scripts

# set permissions in cron
chown -R root:root /etc/cron.d

# Apply sysctl parameters: net.ipv4.ip_forward=1
sysctl --system

# create openvpn user for service
if ! id openvpn &> /dev/null 
then
  adduser --system --no-create-home --group openvpn
fi

# set owner
chown -R root:openvpn /etc/openvpn
chmod -R 640 /etc/openvpn

chown -R openvpn:openvpn /var/log/openvpn

# enable openvpn service
systemctl enable openvpn@server

# nginx remove default site
sudo rm -vf /etc/nginx/sites-enabled/default
sudo rm -vf /etc/nginx/sites-available/default

# get ip address of test-mon and test-mgmt
vm_mon=$(host test-mon | awk '{print $NF"/32"}')
vm_mgmt=$(host test-mgmt | awk '{print $NF"/32"}')

# clear iptables rules
sudo iptables -F

# set base iptables rules
sudo iptables -P INPUT DROP
sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
sudo iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
sudo iptables -A INPUT -i lo -j ACCEPT

# allow ssh from mgmt
sudo iptables -A INPUT -p tcp -s "$vm_mgmt" --dport 22 -j ACCEPT

# allow vpn from anywhere
sudo iptables -A INPUT -p udp --dport 1194 -j ACCEPT

# allow icmp
sudo iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT

# allow node-exporter (9100/tcp) from mon
sudo iptables -A INPUT -p tcp -s "$vm_mon" --dport 9100 -j ACCEPT

# allow prometheus openvpn-exporter (9976/tcp) from mon
sudo iptables -A INPUT -p tcp -s "$vm_mon" --dport 9976 -j ACCEPT

# set NAT for VPN
sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

# save iptables rules
sudo service netfilter-persistent save

exit 0